### ISSUE TITLE
4 spaces indentation

### ISSUE THREAD

**Issue by louis-cuny** [fangpsh/ngxfmt#6]
According to nginx configuration coding standards, the indentation should be with 4 spaces.
There is other things to improve but 4 spaces seems important.

http://nginx.org/en/docs/dev/development_guide.html#code_style

Maybe add an optional parameter like for composer normalize. Example : `composer-normalize --dry-run --indent-size=4 --indent-style=space`

But I would recommand to use ngin coding standards by default

**Comment by fangpsh** [comment]
thanks.
for the moment , you can set the INDENT_W parameter at the beginning of `ngxfmt.py`

**Comment by fangpsh** [comment]
Has changed default indent to 4 spaces.
